[2020-03-18T15:10:21.841][ERROR  8352  app] Something went wrong: Error: Not Found
    at E:\Jie\blog\server\index.js:100:15
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (E:\Jie\blog\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at E:\Jie\blog\node_modules\connect-history-api-fallback\lib\index.js:18:14
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
[2020-03-18T15:11:11.108][ERROR  9044  app] Something went wrong: Error: Not Found
    at E:\Jie\blog\server\index.js:100:15
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (E:\Jie\blog\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at E:\Jie\blog\node_modules\connect-history-api-fallback\lib\index.js:18:14
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
[2020-03-18T19:46:56.115][ERROR  10784  app] Something went wrong: Error: Not Found
    at E:\Jie\blog\server\index.js:100:15
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at serveStatic (E:\Jie\blog\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at E:\Jie\blog\node_modules\connect-history-api-fallback\lib\index.js:18:14
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
[2020-03-18T19:47:45.809][ERROR  10600  app] Something went wrong: ReferenceError: value is not defined
    at Object.getTime (E:\Jie\blog\server\common.js:152:32)
    at exports.add_kind (E:\Jie\blog\server\controllers\article.js:225:26)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Jie\blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Jie\blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Jie\blog\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Jie\blog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
[2020-03-18T19:48:50.054][ERROR  7752  app] Something went wrong: ReferenceError: value is not defined
    at Object.getTime (E:\Jie\blog\server\common.js:152:32)
    at exports.add_kind (E:\Jie\blog\server\controllers\article.js:225:26)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Jie\blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Jie\blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Jie\blog\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Jie\blog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
[2020-03-18T19:49:10.495][ERROR  2788  app] Something went wrong: ReferenceError: value is not defined
    at Object.getTime (E:\Jie\blog\server\common.js:152:32)
    at exports.add_kind (E:\Jie\blog\server\controllers\article.js:225:26)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Jie\blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Jie\blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Jie\blog\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Jie\blog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
[2020-03-18T19:49:29.976][ERROR  10832  app] Something went wrong: ReferenceError: value is not defined
    at Object.getTime (E:\Jie\blog\server\common.js:152:32)
    at exports.add_kind (E:\Jie\blog\server\controllers\article.js:225:26)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Jie\blog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\Jie\blog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (E:\Jie\blog\node_modules\express\lib\router\index.js:174:3)
    at router (E:\Jie\blog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (E:\Jie\blog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (E:\Jie\blog\node_modules\express\lib\router\index.js:317:13)
    at E:\Jie\blog\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Jie\blog\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Jie\blog\node_modules\express\lib\router\index.js:275:10)
